#Makefile for Eric Wang
#assignment 2

all: gr1 gr2 sort
		
gr1: grep1.c
		gcc -g -Wall -o grep1 grep1.c
		
gr2: grep2.c
		gcc -g -Wall -o grep2 grep2.c
		
sort: sort.c
		gcc -g -Wall -o sort sort.c
		
clean: 
		$(RM) grep1
		$(RM) grep2
		$(RM) sort