#Makefile for Eric Wang
#assignment 1

all: as1 pas
		
as1: assign1e.c
		gcc -g -Wall -o assign1e assign1e.c
		
pas: Assign1.c
		gcc -g -Wall -o assign1 Assign1.c
		
clean: 
		$(RM) assign1
		$(RM) assign1e